import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-main_black h-screen w-screen'>
        <main className='mx-auto w-[1220px] h-[662px]'>
          <Navbar></Navbar>
          {children}
        </main>
      </body>
    </html>
  );
}
